name: build_on_release

on:
  workflow_dispatch:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published]
  push:
  pull_request:
    branches: [ master ]

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run my sctipt
      uses: actions/github-script@v4
      id: my-script
      with:
        script: console.log(context.release)
