name: build_on_release

on:
  workflow_dispatch:
  release:
    types: [published]


jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run my sctipt
      uses: actions/github-script@v4
      id: my-script
      with:
        script: console.log(context.payload.release.tag_name)
