name: test_code

on:
    workflow_dispatch:
    push:
        branches: [ master ]
    pull_request:

jobs:
    test_and_build:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout repository
            uses: actions/checkout@v2

        -   name: Caching
            uses: actions/cache@v2
            with:
                path: ~/go/pkg/mod
                key: go-${{ hashFiles('**/go.sum') }}
                restore-keys: |
                    go-
        -   name: Set up Go
            uses: actions/setup-go@v2
            with:
                go-version: 1.16

        -   name: Test
            run: go test -v ./...

        -   name: Docker Layer Caching
            uses: satackey/action-docker-layer-caching@v0.0.11

        -   name: Try to build Docker image
            uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
            with:
                context: .

